#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Feb  7 11:58:27 2020


"""

# wireframe plot for amplitude of wave function for two dimensional potential well
nx=1
ny=1
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
fig=plt.figure()
ax = plt.axes(projection='3d')
x=np.linspace(0,np.pi,500)
y=np.linspace(0,np.pi,500)
x,y=np.meshgrid(x,y)
z=np.sin(nx*x)**2*np.sin(ny*y)**2 # amplitude of wavefunction for two dimensional box
ax.plot_wireframe(x, y, z, color='red')
ax.set_title('wireframe plot for wavefunction amplitude')
plt.show()